version: '3'

services:

  mysql-server:
    image: mysql:8.0.33
    container_name: template_mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - template_project

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "8080:80"
    networks:
      - template_project

volumes:
  mysql-data:

networks:
  template_project: